services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - admin_db
  admin_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: microservice_admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: magynevy@11055
      MYSQL_ROOT_PASSWORD: magynevy@11055
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - "33063:3306"